import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Notification from "@/components/toastifyNotification/notification";
import { LoadingProvider } from "./loadingContext";
import Loading from "./loading";
import { cn } from "@/lib/utils";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import ReduxProvider from "@/redux/provider";

// const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });
// const geistMono = Geist_Mono({ subsets: ["latin"], variable: "--font-mono" });

const arimaSans = localFont({
  src: "./fonts/Arima-Light.ttf",
  variable: "--font-arima-sans",
  weight: "100 900",
});
const arimaMono = localFont({
  src: "./fonts/Arima-Light.ttf",
  variable: "--font-arima-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "EzzyShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(GeistSans.variable, GeistMono.variable, "font-sans")}
    >
      <body className={`${arimaSans.variable} ${arimaMono.variable}`}>
        <ReduxProvider>
          <LoadingProvider>
            <Notification />
            {children}
            <Loading /> {/* Global Loading component */}
          </LoadingProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
